### ISSUE TITLE
Pagy::Frontend::I18N.load_file Error

### ISSUE THREAD

**Issue by msdundar** [ddnexus/pagy#57]
After updating pagy from '0.10.1` to `0.11.2`, the line shown below started to throw errors:

_config/initializers/pagy.rb_

```ruby
Pagy::Frontend::I18N.load_file('config/locales/gems/pagy/tr.yml') # load a custom file
```

Here is the full error description:

```
Traceback (most recent call last):
	58: from bin/rails:6:in `<main>'
	57: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	56: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	55: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	54: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	53: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	52: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	51: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	50: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	49: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
	48: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	47: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	46: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	45: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	44: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	43: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:95:in `perform'
	42: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	41: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
	40: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	39: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	38: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	37: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	36: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	35: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	34: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	33: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	32: from /home/serhat/projects/nokul/config/environment.rb:7:in `<main>'
	31: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	30: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	29: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	28: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	27: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	26: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	25: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	24: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	23: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	22: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `call'
	21: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	20: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	19: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	18: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	17: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	16: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	15: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	14: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	13: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	12: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	11: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:613:in `block in <class:Engine>'
	10: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:613:in `each'
	 9: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	 8: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:656:in `load_config_initializer'
	 7: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
	 6: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 5: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	 4: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	 3: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	 2: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 1: from /home/serhat/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/serhat/projects/nokul/config/initializers/pagy.rb:55:in `<main>': undefined method `load_file' for #<Hash:0x000055858a2ba510> (NoMethodError)
```

**Comment by ddnexus** [comment]
Hi @msdundar 
sorry for the issue, but there has been some simple to fix [breaking changes](https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md#version-0110) in version 0.11.0. Please, follow the CHANGELOG link to update. Please, let me know if I can help.

Besides, I just noticed that the CHANGELOG missed to report to update also the [initializer file](https://github.com/ddnexus/pagy/blob/master/lib/pagy/extras/initializer_example.rb#L58). I will fix the CHANGELOG.

Thanks

**Comment by ddnexus** [comment]
Updated the CHANGELOG (1f3087b62260f1e10e4560e7df46d3dde2be5b11)

**Comment by ddnexus** [comment]
@msdundar 
I saw that you are using a custom language. The new Pagy version has been refactored in order to better support custom i18n, especially with regard to multiple languages and relative pluralization.

If the file you are using is generic (i.e. suitable for general use), then you could add your file to the bottom of the [pagy.yml](https://github.com/ddnexus/pagy/blob/master/lib/locales/pagy.yml) file and create a pull request. ;)

If your language doesn't use the same `"en"` default pluralization types (i.e. 'zero', 'one', 'other'), you should also add a proc in the [ plurals.rb](https://github.com/ddnexus/pagy/blob/master/lib/locales/plurals.rb), so it will be properly pluralized by pagy i18n.

Please, let me know if I can help. Thanks

**Comment by msdundar** [comment]
Thanks for your quick reply, detailed explanation and update on CHANGELOG.

I will make a PR for translations soon. My issue is fixed, after changing the initializer as shown below:

```ruby
Pagy::Frontend::I18N.load(file:'config/locales/gems/pagy/tr.yml', language:'tr')
Pagy::Frontend::I18N.load(file:'config/locales/gems/pagy/en.yml', language:'en')
```

best regards.

**Comment by ddnexus** [comment]
I suppose that the 2 lines are from 2 apps, right? Because there is no support for dynamic translation of multiple languages in the current pagy I\ internal i18n. And if you are using the `i18n` extra (i.e. the canonical I18n gem), then that 2 lines are not used at all by the pagination.

**Comment by msdundar** [comment]
In fact, they are from the same application and it worked well :) I am not using any additional translation-globalization GEMs, just default i18n bundled with Rails and ActiveSupport. When I switch between locales I can see the translated pagination texts without any problems.

**Comment by ddnexus** [comment]
Thanks for the explanation. Then it looks like you are using the `i18n` extra... and I just understood that my doc is not clear enough then :).

I will update also the `initializer_example.rb` to make it more clear.

You don't need that 2 lines if you use the `i18n` extra, because your app is using the canonical I18n gem included as a dependency of rails, hence that 2 lines are totally ignored by the I18n gem.

**Comment by ddnexus** [comment]
Updated initializer_example.rb (cdab354d5d39b5a8ecfae15e2317bc96f83fb3d4)
