### ISSUE TITLE
Bug: Crashes when running rails server after upgrade

### ISSUE THREAD

**Issue by matthewblott** [ddnexus/pagy#731]
### 👀 Before submitting...

- [X] I upgraded to pagy version 9.0.5
- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### 🧐 REQUIREMENTS

- [X] I am providing a VALID code file that confirms the bug
- [X] I am NOT posting any of the USELESS THINGS listed above
- [X] I am aware that this issue will be automatically closed if the code file is missing or INVALID

### 💬 Description

I tried to upgrade from Pagy 7.0 to 9.0.5 but when I run `rails s` I receive the following error:
```bash
/Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- pagy/extras/support (LoadError)
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/Matt/Development/northwind-rails-hotwire/config/initializers/pagy.rb:1:in `<top (required)>'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/engine.rb:689:in `load'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/engine.rb:689:in `block in load_config_initializer'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/notifications.rb:212:in `instrument'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/engine.rb:688:in `load_config_initializer'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/engine.rb:642:in `block (2 levels) in <class:Engine>'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/engine.rb:641:in `each'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/engine.rb:641:in `block in <class:Engine>'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:32:in `run'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:425:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:424:in `block in each_strongly_connected_component_from'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:50:in `each'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:418:in `call'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:418:in `each_strongly_connected_component_from'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `call'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/application.rb:428:in `initialize!'
	from /Users/Matt/Development/northwind-rails-hotwire/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block (2 levels) in <top (required)>'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:108:in `eval'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:108:in `new_from_string'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:97:in `load_file'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:67:in `parse_file'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:73:in `perform'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:71:in `block in invoke'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/Matt/.local/share/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
```
I tried installing version 8.0 and the same error occurs so it appears to be a compatibility issue between 7.0 and 8.0. I did search through the discussions and categories but I couldn't find any notes on upgrading. Any help appreciated :-)

**Comment by benkoshy** [comment]
Check your `config/initializers/pagy.rb` file.

```rb
require 'pagy/extras/support'
```

Where is the 'support' extra in pagy?

**Comment by ddnexus** [comment]
Try with `pagy/extras/pagy`.

The 'support' has been refactored and merged with other code.

Documented [here](https://github.com/ddnexus/pagy/blob/master/CHANGELOG_LEGACY.md#breaking-changes)
